#!/bin/bash
# Debug script to analyze crawler behavior

echo "=== Crawler Debug Analysis ==="
echo ""
echo "This will help diagnose why the crawler stops at 309 pages."
echo ""
echo "Please run your crawler and check the logs for these patterns:"
echo ""
echo "1. Look for '[QUEUE EXHAUSTED]' message - this indicates no more links were found"
echo "2. Check '[QUEUE]' messages - see if 'New: 0' appears frequently (no new links discovered)"
echo "3. Look at '[STATS]' every 50 pages - check the Filtered and Duplicates counts"
echo "4. Check '[DISCOVERY]' messages - see if sitemap URLs were found"
echo ""
echo "Common reasons for stopping at 309:"
echo "  - Website only has 309 pages accessible via internal links"
echo "  - Remaining pages require JavaScript navigation"
echo "  - Pages are behind authentication/forms"
echo "  - Pages use query parameters that vary (pagination, filters, etc.)"
echo "  - Pages are in a different subdomain"
echo ""
echo "To get more details, enable RUST_LOG=debug before running:"
echo "  RUST_LOG=debug cargo run --release -- crawl <URL>"
